#!/bin/bash
SCRIPT="#!/bin/bash\n
PATHFILE=/etc/crontab\n
if [ ! -f /home/vagrant/lastModif.txt ]\n
then\n
	echo \"init\" > /home/vagrant/lastModif.txt\n
fi\n
LASTMODIF=\`cat /home/vagrant/lastModif.txt\`\n
CMDLASTMODIF=\`stat \$PATHFILE -c %Y\`\n
if [ \$CMDLASTMODIF != \$LASTMODIF ]\n
then\n
	echo \"file /etc/crontab has been modified \" | mail -s \"hello\" root\n
	echo \$CMDLASTMODIF > /home/vagrant/lastModif.txt\n
fi"
echo -e $SCRIPT > /home/vagrant/detectModif.sh

sudo crontab -l | echo "0 0 * * * bash /home/vagrant/detectModif.sh" | sudo crontab
