#!/bin/bash

PATHFILE=/etc/crontab
LASTMODIF=`cat /home/vagrant/lastModif.txt`
CMDLASTMODIF=`stat $PATHFILE -c %Y`

if [ $CMDLASTMODIF != $LASTMODIF ]
then
	echo "file /etc/crontab has been modified " | mail -s "hello" "thifranc42@gmail.com"
	echo $CMDLASTMODIF > /home/vagrant/lastModif.txt
else
	echo "non changé"
fi
